### ISSUE TITLE
Package bundle missing `server.ts` file

### ISSUE THREAD

**Issue by bayssmekanique** [QwikDev/astro#1]
When attempting to use the package, the server code fails with this error:
```
Failed to load url @qwikdev/astro/server (resolved id: @qwikdev/astro/server). Does the file exist?
```

When looking at the installed `@qwikdev/astro` directory, there is no `server.ts` file in the bundle.

![image](https://github.com/QwikDev/astro/assets/2280384/acf85f86-d25a-44f6-919d-06795b1f8f37)

**Comment by thejackshelton** [comment]
fixed in 0.0.27
