### ISSUE TITLE
Hooks for Astro runtime API

### ISSUE THREAD

**Issue by grumpyTofu** [QwikDev/astro#122]
Is there any interest in building the equivalent of the qwik-city hooks like useLocation but for the astro integration?
I am struggling to access the Astro runtime API in qwik components:
https://docs.astro.build/en/reference/api-reference/

**Comment by thejackshelton** [comment]
Hey @grumpyTofu! 

If there's a "Astro" way to do this, then that's always preferred since Astro is the meta-framework of choice here.

I do think that this would be important to have in the integration (if this functionality is missing or unintuitive). I'll be happy to review any PR's 👍

**Comment by grumpyTofu** [comment]
Thanks for the quick response @thejackshelton! I've had success getting the values from the Astro API and passing in values as props to my qwik components. This seems to be the most reliable, but ideally my qwik components would not have to have a dependency on an Astro wrapper. I would be down to write some utility hooks, but I have been running into some issues with what I have so far.

I have written an example hook that seems to work okay. I noticed that the `astro:page-load` and `astro:after-swap` events do not trigger for view transitions, but the document `load` event seems to catch all of them. Have you heard of any similar issues related to view transition events with astro?

```ts
export const usePathname = () => {
  const pathname = useSignal("");

  const updatePathname = $(() => {
    pathname.value = window.location.pathname;
  });

  useOnDocument("astro:page-load", updatePathname);
  useOnDocument("astro:after-swap", updatePathname);
  useOnDocument("load", updatePathname);

  return pathname;
};
```

The final issue I noticed while testing was when I used this hook to toggle some other signal values with the following code:

```ts
const active = useSignal(false);
useVisibleTask$(({ track }) => {
  track(() => pathname.value);
  active.value = Boolean(href && pathname.value === "/");
});
```

On initial load, it works perfectly. However, if you navigate to a new page, I get the following errors:

<img width="840" alt="image" src="https://github.com/QwikDev/astro/assets/30991516/e313b58f-656b-4b6f-a5d8-20116f91a274">

I am not sure if this is because I am a qwik noob, or if there is an actual bug here. Any insight that you can provide?

**Comment by thejackshelton** [comment]
> Thanks for the quick response @thejackshelton! I've had success getting the values from the Astro API and passing in values as props to my qwik components. This seems to be the most reliable, but ideally my qwik components would not have to have a dependency on an Astro wrapper. I would be down to write some utility hooks, but I have been running into some issues with what I have so far.
> 
> I have written an example hook that seems to work okay. I noticed that the `astro:page-load` and `astro:after-swap` events do not trigger for view transitions, but the document `load` event seems to catch all of them. Have you heard of any similar issues related to view transition events with astro?
> 
> ```ts
> export const usePathname = () => {
>   const pathname = useSignal("");
> 
>   const updatePathname = $(() => {
>     pathname.value = window.location.pathname;
>   });
> 
>   useOnDocument("astro:page-load", updatePathname);
>   useOnDocument("astro:after-swap", updatePathname);
>   useOnDocument("load", updatePathname);
> 
>   return pathname;
> };
> ```
> 
> The final issue I noticed while testing was when I used this hook to toggle some other signal values with the following code:
> 
> ```ts
> const active = useSignal(false);
> useVisibleTask$(({ track }) => {
>   track(() => pathname.value);
>   active.value = Boolean(href && pathname.value === "/");
> });
> ```
> 
> On initial load, it works perfectly. However, if you navigate to a new page, I get the following errors:
> 
> <img alt="image" width="840" src="https://private-user-images.githubusercontent.com/30991516/332243179-e313b58f-656b-4b6f-a5d8-20116f91a274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTUxNTMsIm5iZiI6MTcxNjI1NDg1MywicGF0aCI6Ii8zMDk5MTUxNi8zMzIyNDMxNzktZTMxM2I1OGYtNjU2Yi00YjZmLWE1ZDgtMjAxMTZmOTFhMjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjI0NzI0NzMxNWQxMDMzZWQ0NmJjODFmOGM0NDcwZWEwZDY0NGU3MjY1YTJkZTY5OWVhZDY4ZTMzNzVlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrNiB8NLnrQTfbQ4zCxxrC6khZLvqTbwkxWt2aoC3D8">
> I am not sure if this is because I am a qwik noob, or if there is an actual bug here. Any insight that you can provide?

If you're using useVisibleTask$ with view transitions it might be related to https://github.com/QwikDev/astro/issues/80

**Comment by thejackshelton** [comment]
Hey @grumpyTofu! Have you played with the new Astro container API?

I have been swamped lately. Trying to find time to improve the integration whenever I can. 

I have just added a continuous release system, so any commit or PR made to the project can be consumed in your own Astro project.

If you'd like to take a stab at something let me know 👍

**Comment by thejackshelton** [comment]
Closed due to inactivity. Astro handles this use case.
