### ISSUE TITLE
Qwik 1.5.7 causes build fail

### ISSUE THREAD

**Issue by thejackshelton** [QwikDev/astro#128]
Astro seems to add an assetsDir for you out of the box. In 1.5.7 the qwikVite plugin `outDir` logic was changed based on if the `assetsDir` existed, causing a failing build.

The current workaround is to downgrade to Qwik 1.5.6 in your `@qwikdev/astro` application

package.json:
```
    "@builder.io/qwik": "1.5.6",
```

**Comment by thejackshelton-kunaico** [comment]
Fixed
