### ISSUE TITLE
How to integrate Qwik and React integrations when jsxImportSource is a single valued string?

### ISSUE THREAD

**Issue by laurencefass** [QwikDev/astro#135]
I think that there may be a conflict between React and Qwik astro integrations. Im following through the install 

https://qwik.dev/docs/integrations/astro/

on an existing astro site in which i have previously installed the React integration

https://docs.astro.build/en/guides/integrations-guide/react/

The documented qwik react integration updates tsconfig.json.

{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  }
}

The qwik astro integation requires a manual update:

"compilerOptions": {
  "jsx": "react-jsx",
  "jsxImportSource": "@builder.io/qwik"
}

As jsxImportSource is not an array it can only have one reference. 

Does this mean we cant install React alongside Qwik?

Is it possible to use a combo of folder and file extensions e..g. components/react/.*.react.tsx and components/qwik/*.qwik.tsx to process both?

**Comment by siguici** [comment]
You can [see the `using multiple JSX frameworks` section from the README](https://github.com/QwikDev/astro?tab=readme-ov-file#using-multiple-jsx-frameworks).

**Comment by laurencefass** [comment]
? but i still need to include 

/** @jsxImportSource @builder.io/qwik */

in all of my qwik files so what does the config integration do?

**Comment by siguici** [comment]
Hey @laurencefass.
Indeed, you will have to define your preferred TSX framework in your `tsconfig.json` then specify the TSX for each component although you specified it in your Astro configuration file. This is due to the fact that you may want to mix various TSX components in the same directory. Astro must know which rule to apply for each component.
