### ISSUE TITLE
Base url issue?

### ISSUE THREAD

**Issue by wirhabenzeit** [QwikDev/astro#137]
I just tried adding `qwikdev()` to my integrations of an existing astro project (astro 4.11.0, @qwikdev/astro 0.5.16, @builder.io/qwik 1.5.6).

Everything works great in dev mode. However, once I build and preview, I get multiple 404s in the browser like `http://localhost:4321/base/_astro/hoisted.DwPdqVDm.js net::ERR_ABORTED 404 (Not Found)` and basically all client side javascript stops working. 

When I look at my `dist` directory it looks like 
```
_astro/
qwik-prefetch-service-worker.js
base/
   qwik-prefetch-service-worker.js
   _astro/
```
with `qwikdev()` while without `qwikdev()` the `base` folder does not exist in the `dist` directory. 

The configuration of the base url is set with `base: "/base"` in `astro.config.ts`. Is there anything I can do fix the `qwikdev` integration to work with my base url setup? Or is this a bug in in the integration?

**Comment by thejackshelton** [comment]
Try Qwik Astro 0.6 and Qwik 1.7.1, do you still get the issue?

**Comment by thejackshelton** [comment]
Closing. Happy to take another look with a minimal reproduction on the latest versions, as I know the logic here has changed in core.
