### ISSUE TITLE
Use @qwikest/icons inside Astro component cause error

### ISSUE THREAD

**Issue by zougari47** [QwikDev/astro#142]
When I try to use a component from `@qwikest/icons` inside Astro component I get this error.
`Unable to render LuBook. No valid renderer was found for this file extension.`

Here is a [minimal production](https://stackblitz.com/edit/withastro-astro-wrw3hw?file=src%2Fpages%2Findex.astro,astro.config.mjs)

**Comment by thejackshelton** [comment]
@zougari47 think I've found the issue, the icons are inline components! Which the integration currently doesn't account for. I'll try to see how to approach this 🤔

**Comment by thejackshelton** [comment]
I think the workaround right now is to import them in Qwik files, but I will try to see how we can account for inline components.

**Comment by zougari47** [comment]
Yes. That is what I ended up doing. reexport icons I want inside a Qwik component.
```tsx
import { component$ } from '@builder.io/qwik'
import {
  LuBook,
  LuGitPullRequest,
  LuCircleDot,
  LuHome,
} from '@qwikest/icons/lucide'

const BookIcon = component$(() => <LuBook />)
const GitPullRequestIcon = component$(() => <LuGitPullRequest />)
const CircleDotIcon = component$(() => <LuCircleDot />)
const HomeIcon = component$(() => <LuHome />)

export { BookIcon, GitPullRequestIcon, CircleDotIcon, HomeIcon }

```
