### ISSUE TITLE
[0.6.3] - Inline Components still throwing "No matching renderer found" error

### ISSUE THREAD

**Issue by eels** [QwikDev/astro#158]
Hello! 

Apologies if you'd rather I re-open the existing issue relating to this problem (#142) rather than creating a new one. I saw that the latest release (0.6.3) looks to add support for inline-components (#149), but it seems like the issue is still present.

Here's a minimal reproduction copied from the demos package.

https://stackblitz.com/edit/github-gsz2jq?file=src%2Fpages%2Findex.astro

Let me know if I'm doing anything dumb, which to be honest I very well could be doing!

**Comment by eels** [comment]
So after a little more experimentation and digging it seems like 0.6.3 works on the Astro dev server so long as you also import a locally defined Qwik component. Further research shows that this local component only needs to be imported and doesn't even need to actually be used in the template.

**Astro Component w/ Inline Component Only**
https://stackblitz.com/edit/github-gsz2jq?file=src%2Fpages%2Findex.astro

**Astro Component w/ Inline Component + Local Qwik Component Imported + Included in Template**
https://stackblitz.com/edit/github-gsz2jq-x8ssem?file=src%2Fpages%2Findex.astro

**Astro Component w/ Inline Component + Local Qwik Component Imported Only**
https://stackblitz.com/edit/github-gsz2jq-hadbrp?file=src%2Fpages%2Findex.astro

However, these scenarios only seem to work when running the dev server. When attempting a production Astro build the following error is still thrown for all examples.

> There is 1 renderer configured in your `astro.config.mjs` file, but it was not able to server-side render `LuCheck`.

Again, caveating this with me potentially doing something stupid. 🙃

**Comment by thejackshelton** [comment]
This should be fixed in the latest version. Let me know if that's not the case! Happy to re-open if so.
