### ISSUE TITLE
npm create @qwikdev/astro CLI fails when installing dependencies 

### ISSUE THREAD

**Issue by Shane-Donlon** [QwikDev/astro#167]
It seems the CLI is not working for astro qwik see below terminal output at the end of this
Observation is that when I'm installing dependencies' it is NOT changing directory into the newly created folder before running npm install.

solution is to cd into folder then run npm install and everything works.

As a side note.
The astro.config.ts after I use node adapter has the below output

****
astro.config.ts output
****

import qwik from "@qwikdev/astro";
import { defineConfig } from "astro/config";

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({
    mode: "standalone",
  }),
  integrations: [qwik()],
});

can this be updated to qwikdev ?
I know it is a default export so no problems, but just to be consistent with the document found at [https://qwik.dev/docs/integrations/astro/](https://qwik.dev/docs/integrations/astro/)

***
Update from documentation
***
  // astro.config.mjs

  import { defineConfig } from 'astro/config';
+ import qwikdev from '@qwikdev/astro';
 
  export default defineConfig({
    // ...
    integrations: [qwikdev()],
    //             ^^^^^
  });

****
Output for CLI ****
>  npm create @qwikdev/astro
> npx
> create-astro

┌  Let's create a  QwikDev/astro App  ✨
│
◇  Where would you like to create your new project? (Use '.' or './' for current directory)
│  ./qwik-astro-app
│
◇  Which adapter do you prefer?
│  Node
│
◇  Would you prefer Biome over ESLint/Prettier?
│  Yes
│
◇  Creating new project in  ${location of stuff}  ... 🐇
│
◇  Would you like to add CI workflow?
│  No
│
◇  Would you like to install npm dependencies?
│  Yes
│
◇  Installing dependencies...
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on ChildProcess instance at:
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ]
}

Node.js v22.11.0
npm error code 1
npm error path ${location of stuff}
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c create-astro
npm error A complete log of this run can be found in: ${location of stuff}

**Comment by siguici** [comment]
Hi @Shane-Donlon,  

Sorry for the delay in my response.  

The error `spawn npm ENOENT` typically occurs when the system cannot locate the `npm` command. 

Here’s a single set of instructions to help you resolve the issue:  

1. Check if Node.js and npm are installed:

```bash
node -v
npm -v
```

If not installed, download and install from https://nodejs.org.

2. Ensure npm is in your PATH

On Windows, ensure "C:\Program Files\nodejs" is in the PATH environment variable.
Restart your terminal after making changes.

3. Use `npx` to run `@qwikdev/create-astro` directly

```bash
npx @qwikdev/create-astro@latest
```

4. Update npm to the latest version

```bash
npm install -g npm
```

5. If issues persist, check the error logs

Refer to the logs at the location mentioned in the error message for more details.

6. As a last resort, reinstall Node.js

Uninstall Node.js completely and reinstall it from https://nodejs.org.

**Comment by Shane-Donlon** [comment]
@siguici Hey Sigui, thanks for getting back to me. 😄 
Does it work for you?

To be clear this is the create  Astro with Qwik command, not the add Qwik to an existing Astro Project command.
Go to anywhere and open terminal

then run 
```terminal
npm create @qwikdev/astro
```
Answer  yes on install dependencies'. 

I think I've identified the issue if it fails for you but I haven't been able to test this locally yet as I do not reach the install section of the CLI.


System Info below
```terminal
  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 296.39 MB / 7.74 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.2 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.38 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

```

**Comment by siguici** [comment]
It installs well on Unix systems. I haven't tried them on Windows yet. I think it would be time to test the CLI on all OSes. I'm working on it now.

I'll make sure the current version works well on Windows.

**Comment by siguici** [comment]
@Shane-Donlon,
Try this command on your side and let me know if everything works fine:

```shell
npx https://pkg.pr.new/QwikDev/astro/@qwikdev/create-astro@4bac5a3
```

**Comment by thejackshelton** [comment]
This should be fixed in the latest version. Let me know if that's not the case! Happy to re-open if so.

**Comment by Shane-Donlon** [comment]
> @Shane-Donlon, Try this command on your side and let me know if everything works fine:
> 
> ```shell
> npx https://pkg.pr.new/QwikDev/astro/@qwikdev/create-astro@2a58aa6
> ```
Hey / Salut Sigui,
Sorry about only getting back to you now.

`npx https://pkg.pr.new/QwikDev/astro/@qwikdev/create-astro@2a58aa6` works perfectly on Windows 🥳 

Currently `npm create @qwikdev/astro` still does not work on Windows.


Also as feedback:
The question " What should be the name of this package?"
kind of confused me for a second as it was already given in Q1, although it did pre-fill with "sd" so that was good!

Maybe replace "package" with "project" (2 references)?

Nice work on this..

Hey Jack,
Not sure if you want to reopen this or not?!
Up to you!

********
Output Confirmation
********
```shell
◇  Where would you like to create your new project? (Use '.' or './' for current directory)
│  ./sd
│
◇  Would you like to use a server adapter?
│  Yes
│
◇  Which adapter do you prefer?
│  Node
│
◇  Would you prefer Biome over ESLint/Prettier?
│  Yes
│
◇  Would you like to add CI workflow?
│  No
│
◇  Would you like to install npm dependencies?
│  Yes
│
◇  Would you like to initialize Git?
│  No
│
◇  What should be the name of this package?
│  sd
┌  Let's create a  QwikDev/astro App  ✨
│
◇  Creating new project in  ${location of stuff}\sd  ... 🐇
│
◇  Installing dependencies...

added 377 packages, and audited 378 packages in 48s

143 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
│
●  ℹ️ Updated package name to "sd" 📦️
│
◇  Ready to start 🚀 ───────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│  🦄  Success!  Project created in  ${location of stuff}/sd directory  │
│                                                                                           │
│  🐰 Next steps:                                                                           │
│     cd ${location of stuff }sd                                       │
│     npm start                                                                             │
│                                                                                           │
├───────────────────────────────────────────────────────────────────────────────────────────╯
│
└  Happy coding! 💻🎉

**Comment by siguici** [comment]
Hey @Shane-Donlon,

> Also as feedback: The question " What should be the name of this package?" kind of confused me for a second as it was already given in Q1, although it did pre-fill with "sd" so that was good!
> 
> Maybe replace "package" with "project" (2 references)?
> 

The first question refers to the destination path of the project (e.g., `workspace/apps/my-qwik-astro-app` or simply `"."` to reference the current working directory). On the other hand, the package name refers to the name that will appear in the `name` field of the project's `package.json` file. This is optional, and the placeholder value will be used as the default if left blank.

> Nice work on this..

Thank you for your positive feedback. It’s truly a pleasure. 😊

> Hey Jack, Not sure if you want to reopen this or not?! Up to you!
> 

Try using `npm create @qwikdev/astro@latest`. I'll also ensure that the tests work seamlessly across all environments.
