### ISSUE TITLE
SRC Dir not found - testing new version

### ISSUE THREAD

**Issue by Shane-Donlon** [QwikDev/astro#172]
Hey Jack -  I am getting a src dir not found error from Qwik srcDir
```powershell
npm run dev
> grateful-galaxy@0.0.1 dev
> astro dev
SRC DIR: {location of stuff on my computer}/src/
16:24:30 [types] Generated 5ms
Qwik srcDir " {location of stuff on my computer}/src" not found.
Stack trace:
    at Object.validateSource (file:///{location of stuff on my computer}/node_modules/@builder.io/qwik/dist/optimizer.mjs:2092:17)
    at async Promise.all (index 4)
    at async EnvironmentPluginContainer.buildStart (file:///{location of stuff on my computer}/node_modules/astro/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:46903:5)
    at async httpServer.listen (file{location of stuff on my computer}/node_modules/astro/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:43701:9)
```

System info taken - (PS if this command was taken from Qwik repo issue, if you have an updated command I don't mind running it before submitting issues)

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 611.89 MB / 7.74 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @builder.io/qwik: ^1.11.0 => 1.11.0

package.json
```json
  "dependencies": {
    "astro": "^5.0.1",
    "@builder.io/qwik": "^1.11.0",
    "@qwikdev/astro": "https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@257b7d8"
  }
```

also an issue with this package.json
```json
"dependencies": {
    "astro": "5.0.0-beta.12",
    "@builder.io/qwik": "^1.11.0",
    "@qwikdev/astro": "https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@257b7d8"
  }
```
steps to reproduce

npm create astro@latest

update package.json
```json
    "@builder.io/qwik": "^1.11.0",
    "@qwikdev/astro": "https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@257b7d8"
```
npm install
```mjs
import qwikdev from "@qwikdev/astro";
export default defineConfig({
  integrations: [qwikdev()],
});
```

npm run dev
Dev server doesn't start due to error above

some confirming points

- I am in the project root directory
- the src folder exists
- node_modules/@qwikdev/astro/package.json has the updated contributor names and x.com url etc...
```json
{
  "name": "@qwikdev/astro",
  "description": "Use Qwik components and Resumability within Astro",
  "version": "0.6.3",
  "contributors": [removed ],
  "type": "module",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/QwikDev/astro",
    "directory": "libs/qwikdev/astro"
  },
  "types": "./src/index.ts",
  "main": "./src/index.ts",
  "exports": {
    ".": "./src/index.ts",
    "./package.json": "./package.json",
    "./server": "./server.ts",
    "./entrypoints": "./src/entrypoints.ts",
    "./utils": "./src/utils.ts"
  },
  "files": [
    "src",
    "src/index.ts",
    "server.ts",
    "env.d.ts"
  ],
  "keywords": [
    "astro-integration",
    "astro-component",
    "renderer",
    "withastro",
    "performance",
    "perf",
    "optimization",
    "qwik"
  ],
  "publishConfig": {
    "access": "public"
  },
  "bugs": "https://github.com/thejackshelton/@qwikdev/astro/issues",
  "dependencies": {
    "astro-integration-kit": "^0.16"
  },
  "devDependencies": {
    "@builder.io/qwik": "^1.10",
    "astro": "5.0.0-beta.12",
    "vite": "^5.4.11"
  },
  "peerDependencies": {
    "@builder.io/qwik": "^1.10"
  }
}

```

**Comment by thejackshelton-kunaico** [comment]
Looking into this 🫡

**Comment by thejackshelton** [comment]
Looking into this 🫡

**Comment by thejackshelton-kunaico** [comment]
@Shane-Donlon can you go ahead and try this version?

https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@bafc173

**Comment by Shane-Donlon** [comment]
@thejackshelton @thejackshelton-kunaico Not sure which one to tag here 🤣

Confirmed [https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@bafc173 ](https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@bafc173 ) as working

node_modules@qwikdev/package.json 
````json
  "name": "@qwikdev/astro",
  "description": "Use Qwik components and Resumability within Astro",
  "version": "0.6.3",
````

For the sake of transparency this is what and how I have tested (JSX not TSX)
I can confirm that this is working in dev and prod (pushed to Netlify)

(these are all component$ so that obviously works too 🤣 🤣 )
![list of components and hooks that have passed tests](https://github.com/user-attachments/assets/80b4b404-c4ff-4516-917b-548f76f3e1b5)



Note: 
1. the repo is private and the only reason this is private is that it is full of bad practices in order to just confirm things are working, and I don't want people to think it's a documentation repo.
I'll keep adding to it over time but if you need it just let me know and I can share it with you no problem. 

2.  "astro": "5.0.0-beta.12", is in the node modules package.json dev dependencies, not sure if you want to change this to exclude the beta before final release.

  "astro": "^5.0.2" is what is installed on my root package.json as of this morning as I had to run npm create astro etc.....

Node Modules Package.json 
````json
  "devDependencies": {
    "@builder.io/qwik": "^1.10",
    "astro": "5.0.0-beta.12",
    "vite": "^5.4.11"
  },
````

Root package.json
```json
  "dependencies": {
    "@builder.io/qwik": "^1.11.0",
    "@qwikdev/astro": "https://pkg.pr.new/QwikDev/astro/@qwikdev/astro@bafc173",
    "astro": "^5.0.2"
  }
````

**Comment by Shane-Donlon** [comment]
confirmed  dev dependencies 

```json

 "devDependencies": {
    "@builder.io/qwik": "^1.11",
    "astro": "5.0.2",
    "vite": "^5.4.11"
  },
```


update on the tests styles are working too.
![list of components and hooks that have passed tests](https://github.com/user-attachments/assets/4a2acca0-58b6-4837-8620-d85ced1815d4)

**Comment by thejackshelton** [comment]
This should be fixed in the latest version. Let me know if that's not the case! Happy to re-open if so.
