### ISSUE TITLE
[BUG] Qwik components not working after deploy to Cloudflare

### ISSUE THREAD

**Issue by iamyuu** [QwikDev/astro#21]
I tried to deploy my apps to Cloudflare, that's works when I'm testing using preview scripts (`wrangler pages dev ./dist`), but when I [deployed](https://jadwalsholat.my.id/) that, I got an error: 

<details>
<summary>
<code>Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nodeType')</code>
</summary>

![LThgu2t1 2023-11-15 at 11 22 AM@2x](https://github.com/QwikDev/astro/assets/45778229/0257c5d9-ecae-472c-977d-35532890c881)

</details>

I tried to compare both of them, but I don't see any difference
related to https://github.com/QwikDev/astro/pull/17#issuecomment-1809425265

**Comment by thejackshelton** [comment]
I was unable to reproduce in the latest version (0.1.15)

https://2e4676d7.test-astro-qwik.pages.dev/

**Comment by iamyuu** [comment]
nvm, fixed on v0.1.15, sorry for this

**Comment by hckhanh** [comment]
> I was unable to reproduce in the latest version (0.1.15)
> 
> https://2e4676d7.test-astro-qwik.pages.dev/
> 
> Are you using the cloudflare ssr adapter or is it static?

Can I use SSR or Static only with Astro + Qwik?

**Comment by thejackshelton** [comment]
> > I was unable to reproduce in the latest version (0.1.15)
> > https://2e4676d7.test-astro-qwik.pages.dev/
> > Are you using the cloudflare ssr adapter or is it static?
> 
> @thejackshelton Can I use SSR or Static only with Astro + Qwik?

You should be able to use both, and the hybrid option.
