### ISSUE TITLE
Error with ViewTransition in Dev

### ISSUE THREAD

**Issue by junpei-8** [QwikDev/astro#34]
### Summary
First and foremost, I'd like to extend my deep appreciation and respect to the team for developing this amazing integration!

I'm encountering an issue when using the ViewTransition with this integration.

![Screenshot 2023-11-26 at 15 12 12](https://github.com/QwikDev/astro/assets/52122683/4a12c6a1-816d-43b8-92db-ebe100632b7c)

The error message displayed in the development environment is:

```
Uncaught SyntaxError: Unexpected token '{' 
```
![Screenshot 2023-11-26 at 15 05 54](https://github.com/QwikDev/astro/assets/52122683/8d487ee1-e465-40c0-bfa7-f57a268ddeb6)
![Screenshot 2023-11-26 at 15 05 36](https://github.com/QwikDev/astro/assets/52122683/33f8a5bb-3c0b-4d9a-a7cb-0de20554acb4)

Interestingly, this issue does not occur when the project is built for production (npm run build && npm run preview).

I would greatly appreciate any insights or assistance in resolving this issue. Thank you!

### Minimal Demo with Stackblitz
- https://stackblitz.com/edit/withastro-astro-kpv8vn?file=src%2Fpages%2Findex.astro

### Environment
- "@astrojs/check": "^0.3.1"
- "@builder.io/qwik": "^1.2.19"
- "@qwikdev/astro": "^0.2.4"
- "astro": "^3.6.0"
- "typescript": "^5.3.2"

**Comment by iivvaannxx** [comment]
I wanted to open an issue too. I think I can provide a bit more context too for this error, as I experiencied a similar one which I think it may be related.

I believe the error is not related to the `ViewTransitions`, but to the `<script>` tag that it may have inside. For some reason the integration seems to interfere with the pasing of [Astro script blocks](https://docs.astro.build/en/guides/client-side-scripts/) and more specifically Typescript.

I had a simple component which used Typescript inside an Astro component `<script>` (not the same that the server frontmatter) and having this integration enabled printed an error on the console complaining about invalid syntax (as if it was expeting JS). It's rare because Astro fully supports using Typescript on client-side script tags.

As soon as I disabled the extension it went away. I think it may be related, but I hadn't time to investigate nor build a minimal reproduction so I didn't open an issue yet.

**Comment by Zareix** [comment]
I also have some other script tags that breaks when using Qwik integration

**Comment by thejackshelton** [comment]
Hey I ran the dev mode of the stack blitz and couldn't see this error. Is there something I'm doing wrong?

What I did see in the console was
```
Uncaught SyntaxError: missing keyword 'from' after import clause [ViewTransitions.astro:1:14](https://withastroastrokpv8vn-fix4-djeynlm0--4321--6843a59c.local-corp.webcontainer.io/node_modules/astro/components/ViewTransitions.astro?astro&type=script&index=0&lang.ts)
```

Does the behavior not work as expected? Is there a set of steps I should follow? Would love to know more so that I can fix this issue.

**Comment by thejackshelton** [comment]
> I also have some other script tags that includes TS which breaks when using Qwik integration I also get following error when building:
> 
> ```
> Error when evaluating SSR module /node_modules/@qwikdev/astro/src/index.ts: failed to import "typescript"
> ...
> Failed to load url typescript (resolved id: typescript) in /Users/[omitted]/node_modules/@qwikdev/astro/src/index.ts. Does the file exist?
> ```

Can you send the script that gives this error? Will try to reproduce.

**Comment by thejackshelton** [comment]
@iivvaannxx I think the problem might be that we have typescript as a dev dependency in the integration.

**Comment by Zareix** [comment]
> > I also have some other script tags that includes TS which breaks when using Qwik integration I also get following error when building:
> > ```
> > Error when evaluating SSR module /node_modules/@qwikdev/astro/src/index.ts: failed to import "typescript"
> > ...
> > Failed to load url typescript (resolved id: typescript) in /Users/[omitted]/node_modules/@qwikdev/astro/src/index.ts. Does the file exist?
> > ```
> 
> Could you make a reproduction of this behavior?

Seems to happen when using SSR : https://stackblitz.com/edit/github-qogdef?file=astro.config.mjs

**Comment by thejackshelton** [comment]
> > > I also have some other script tags that includes TS which breaks when using Qwik integration I also get following error when building:
> > > ```
> > > Error when evaluating SSR module /node_modules/@qwikdev/astro/src/index.ts: failed to import "typescript"
> > > ...
> > > Failed to load url typescript (resolved id: typescript) in /Users/[omitted]/node_modules/@qwikdev/astro/src/index.ts. Does the file exist?
> > > ```
> > 
> > 
> > Could you make a reproduction of this behavior?
> 
> Seems to happen when using SSR : https://stackblitz.com/edit/github-qogdef?file=astro.config.mjs

Are we sure this is a problem with Qwik here? I removed the integration and it seems that we still get an error running dev

https://stackblitz.com/edit/github-qogdef-plfezu?file=astro.config.mjs

**Comment by thejackshelton** [comment]
Ah I was able to reproduce the initial issue, I was using firefox, which is an unsupported browser of view transitions.

**Comment by junpei-8** [comment]
>@junpei-8 Could you confirm by, instead of using View Transitions in your example, adding a client side <script> in your Astro component which uses Typescript syntax? (like for example declaring an interface). If the error goes away after disabling the integration then we found another very weird error @thejackshelton aside from the already horrible https://github.com/QwikDev/astro/issues/30

I've conducted the verification!

<img width="613" alt="Screenshot 2023-11-30 at 9 26 02" src="https://github.com/QwikDev/astro/assets/52122683/dbf1edfa-a978-48ff-9431-5a6e9c3e1b62">

As @iivvaannxx  speculated, an error occurred even when I removed ViewTransition and instead embedded TypeScript in a script.

The error message is different, but like the error that occurs with ViewTransition, the error in this test also seems to stem from a failure to properly understand TypeScript syntax.

```
Uncaught SyntaxError: Unexpected strict mode reserved word (at Layout.astro?astro&type=script&index=0&lang.ts:1:7)
```

Minimal Demo with Stackblitz
- https://stackblitz.com/edit/withastro-astro-kpv8vn?file=src%2Fpages%2Findex.astro

**Comment by thejackshelton** [comment]
Tried spotting some potential causes of the issue.

So we do use typescript for the AST parser to get the Qwik entrypoints (dev dependency)

Also this in the tsconfig
https://github.com/QwikDev/astro/blob/main/libs/qwikdev-astro/tsconfig.json#L12

I tried using an alternative parser called acorn to try and remove typescript, but wasn't able to get that working properly.

**Comment by thejackshelton** [comment]
> @thejackshelton It would probably be a good idea trying to ping someone from the Astro team, if you know any collaborator it could probably bring some insight into this, because it's a bit weird and it seems that directly interferes with something on the Astro end.

Agreed. I reached out to Nate from the core team and he mentioned he will take a look today. 

That said, they are also focused on 4.0 right now, so it may not be the best time. When 4.0 is released and 1.2.20 or 1.3 (vite 5 for qwik) is released I'll be upgrading the package.

**Comment by thejackshelton** [comment]
I think we made some progress on this. The `crawlDirectory` function seems to be reading .astro files causing this problem, but when I try to exclude them it doesn't work 🤔 

Nate mentioned it could also be an incompatibility issue with the Astro typescript plugin.

**Comment by thejackshelton** [comment]
Hey @iivvaannxx @Zareix @junpei-8 wanna give an update, this should no longer be an issue in 0.2.9 😄 

Nate from the Astro core team was able to find out that the `qwikVite` plugin in dev mode disables esbuild 😅 . 

JSX and TSX compilation have to be handled by Qwik with the compiler rather than esbuild.

It's possible there might be a way to configure Vite's esbuild settings to avoid conflicts. For now there is a workaround vite plugin that overrides this behavior specifically for this integration.

**Comment by thejackshelton** [comment]
@junpei-8 I got view transitions working with your example

**Comment by iivvaannxx** [comment]
Great news @thejackshelton! Can confirm that it does work in my project too!
