### ISSUE TITLE
fetching data from a remote api blocks the rendering of the page

### ISSUE THREAD

**Issue by brahimABD98** [QwikDev/astro#39]
Hi I've added some data fetching fetching from an external API and I've noticed that the entire page won't render until the data is loaded ,I think I've used the useResource$ hook properly  the code is available  [here](https://github.com/brahimABD98/my-portfolio/blob/feat/visitbook/src/components/VisitBookEntries.tsx)
no spinner at all
small demo
<img alt="demo" src="https://github.com/QwikDev/astro/assets/47871510/35d2d1c0-ccd5-460f-b572-4a72b62be58f" />

**Comment by thejackshelton** [comment]
Yeah so I think we want to use `useResource$` when we want to asynchronously fetch something client side. 

In the case of Astro, we are getting stuff from the server, and so I think we want to go with Astro's way of fetching data on the server.

<img width="676" alt="image" src="https://github.com/QwikDev/astro/assets/104264123/9d5b9493-57ef-4392-a19c-57fd9da3bd6f">

I think we want something like:

```astro
---

// Fetch data from an API
const response = await fetch('https://api.example.com/data');
const data = await response.json();
---

<!-- has a slot -->
<MyQwikComponent>
  <!-- Use the fetched data in your component -->
  <p>Data: {data}</p>
</MyQwikComponent>
```

https://qwik.builder.io/docs/components/state/#useresource

Closing as this behavior seems to be intended. That said, I need to look into this more to help figure out the best practices for using Qwik inside of Astro. Would love to help combine efforts on that 😄

**Comment by brahimABD98** [comment]
@thejackshelton according to docs in static mode this snippet below will fetch data once at build time only :
`const response = await fetch('https://api.example.com/data');`

My goal here was to keep astro in static mode and use Qwik to fetch data on the fly, the way I thought about this was  loading 5kb Qwik component to fetch some data from data would be much simple and less work overall than setting up astro ssr 
no need for any  ssr adapters , self hosting is much simpler 

here's an example
let's say you you have a blog post and you want to add a comment section and you have to load all comment from your api
best case scenario you would enable ssr just for this path  even with that now you are rendering this page over and over just for a comment section which is imo is very wasteful instead you could hook in a Qwik component  that will fetch the data if it's really needed 
 I mean I could be wrong what do you think did I make any sense ?

**Comment by thejackshelton** [comment]
> @thejackshelton according to docs in static mode this snippet below will fetch data once at build time only so for my use case fetching live data would be useless : `const response = await fetch('https://api.example.com/data');`
> 
> My goal here was to keep astro in static mode and use Qwik to fetch data on the fly, the way I thought about this was loading 5kb Qwik component to fetch some data from data would be much simple and less work overall than setting up astro ssr no need for any ssr adapters , self hosting is much simpler
> 
> here's an example let's say you you have a blog post and you want to add a comment section and you have to load all comment from your api best case scenario you would enable ssr just for this path ,but there's a problem you are rendering this page over and over just for a comment section which is imo is very wasteful instead you could hook in a Qwik component that will fetch the data if it's really needed and I think that would be way better you keep the page as static and you only fetch data if the user need to instead of rendering everything no matter what
> 
> I mean I could be wrong what do you think ?

I think I understand, so you want that specific component instance to client-side fetch that data, but instead it tries to re-render the entire page?

**Comment by brahimABD98** [comment]
My issue revolves around the useResource , which is intended to be non-blocking but is not behaving as expected. Currently, when using useResource to fetch data, it blocks the rendering of other components, such as the sidebar and form, until the data retrieval is complete.

the expected  behavior :
the page should renders promptly without waiting for the completion of the useResource data fetch.  the component responsible for data retrieval should autonomously manage the loading state with this code that I 've already provided
> ` onPending={() => <span class="loading loading-dots loading-lg"></span>}`

**Comment by thejackshelton** [comment]
Update:

Qwik does not have out of order streaming yet, but when it does, you'll be able to see the spinner, and it is planned to be explored after v2 is out (which is an upcoming release).
