### ISSUE TITLE
should context work?

### ISSUE THREAD

**Issue by imoldfella** [QwikDev/astro#41]
When I try to use context with similar code to Qwik City I get this error

QWIK ERROR Error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()

If context does work, would it possible to add it to the demo code as an example?

**Comment by Hunnnn77** [comment]
I struggled same issue, seems astro allows very narrow pattern/solution.
in my case, this only works for me.

```tsx
export const Ctx = createContextId<T>("idhere")

export default component$(() => { // should export to astro file without client:something
  //define context with Ctx
  return <Child />
})

export Child(() => {
  //consume context with Ctx
  return <div>...</div>
})
```

**Comment by imoldfella** [comment]
Thanks! This makes sense in hindsight.
