### ISSUE TITLE
Resume container with Event Listener using Custom Events

### ISSUE THREAD

**Issue by josemarcilio** [QwikDev/astro#48]
I'm trying to use Custom Events instead of nanostores, as the docs recommend.

Given a component Island1 with the setup for triggering an event:

```tsx

export const customEvent = (name: string) =>
  new CustomEvent<string>('awesome', {
    detail: name,
    bubbles: true,
  })

export const Island1 = component$((props) => {
  const divRef = useSignal<HTMLElement>()

  const handleClick$ = $(() => {
    const event = customEvent('Island 1')
    divRef.value?.dispatchEvent(event)
  })

  return (
    <div
      ref={divRef}
      onClick$={handleClick$}
    >
      Island1
    </div>
  )
})
```

And Island2 with the setup for listening:

```tsx
import { $, component$, useOn, useSignal } from '@builder.io/qwik'

export const Island2 = component$((props) => {
  const divRef = useSignal<HTMLElement>()

  useOn(
    'awesome',
    $((event: CustomEvent<string>): void => {
      console.log(event.detail)
    })
  )

  return (
    <>
      <div
        ref={divRef}
      >
        Island2
      </div>
    </>
  )
})

```

I can see the listener was added in dev tools Event Listeners tabs. I works with `useOn` and also with `<div onAwesome$={} />`.
When I click on it, dev tools logs `QWIK Container resumed` for Island1.
But the `console.log` inside the listener never happens. Maybe because Island2 is not resumed?

**Comment by thejackshelton** [comment]
Ah interesting, this is definitely something we need to explore more. If I recall our concerns were that nanostores do not survive serialization, but I think misko found a way to get it working.

 https://stackblitz.com/edit/qwik-starter-tlhhfa?file=src%2Froutes%2Findex.tsx
 
 Really hope to improve the DX of this, but this should work.

**Comment by thejackshelton** [comment]
Also a visible task isn't necessarily needed here, we just need to initialize qwikUseMethodFactory.

We might be able to stick that in a `useTask$`, `useComputed$`, or `sync$`

**Comment by thejackshelton** [comment]
Biggest thing we're working on currently is speculative module fetching / making interactions literally instant in Astro 😄

**Comment by josemarcilio** [comment]
wow, I did think I was missing some obvious thing, but now I can see this is a more complex problem. 

Nice to know you're working on it. I'd like to join you and help because I believe this feature can be very important, but now I am with a 2 months baby in home and he's draining all our time 😅 I'll be back as soon as I can in this subject to get updates. 

Thank you for your help!

**Comment by thejackshelton** [comment]
> wow, I did think I was missing some obvious thing, but now I can see this is a more complex problem.
> 
> Nice to know you're working on it. I'd like to join you and help because I believe this feature can be very important, but now I am with a 2 months baby in home and he's draining all our time 😅 I'll be back as soon as I can in this subject to get updates.
> 
> Thank you for your help!

Congrats on the new baby! Family comes first 😄 

Yeah I agree this is a big piece, once speculative module fetching is added to Astro I want to tackle this next. Look forward to your involvement when you're ready. In the meantime will let you know if I make any progress here on my own.

Nanostores does work, but that code should probably be abstracted away. Also we don't want to use a visible task, that's like a last resort.

**Comment by thejackshelton** [comment]
Here's what I got so far. Looks like it does the job 🤔 

```tsx
import {
  component$,
  type Signal,
  useOnDocument,
  useSignal,
  useTask$,
  $,
  useOn,
} from "@builder.io/qwik";
import { type WritableAtom, atom } from "nanostores";
// @ts-ignore
import { isDev } from "@builder.io/qwik/build";

// global state

const count = atom(123);
const useCount = useNanostore(count, "count");

export const Island1 = component$(() => {
  const count = useCount();
  return <div>Count: {count.value}</div>;
});

export const Island2 = component$(() => {
  const count = useCount();
  return <button onClick$={() => count.value++}>+1</button>;
});

/* @nanostore/qwik */
export function useNanostore<T>(
  atom: WritableAtom<T>,
  name: string
): () => Signal<T> {
  const updateAtomEvent = "ns_set_" + name;
  const notifyQwikName = "ns_notify_" + name;
  let afterInitialSubscription = false;

  atom.subscribe(() => {
    if (afterInitialSubscription && typeof document !== "undefined") {
      document.dispatchEvent(new CustomEvent(notifyQwikName, { detail: atom }));
    }
  });

  afterInitialSubscription = true;

  if (typeof document !== "undefined") {
    document.addEventListener(updateAtomEvent, (event) => {
      const value = (event as CustomEvent<T>).detail;
      console.log(updateAtomEvent, value);
      atom.set(value);
    });
  }

  return function useNanoToQwik() {
    const signal = useSignal(atom.get());
    useTask$(({ track }) => {
      const value = track(() => signal.value);
      if (typeof document !== "undefined") {
        document.dispatchEvent(
          new CustomEvent(updateAtomEvent, { detail: value })
        );
      }
    });

    if (isDev) {
      useOn(
        "qvisible",
        $(() => {
          // initializes in dev when referenced
          useNanostore;
        })
      );
    }

    useOnDocument(
      notifyQwikName,
      $((event) => {
        const atom = (event as CustomEvent<WritableAtom<T>>).detail;
        console.log(notifyQwikName, atom);
        signal.value = atom.get();
      })
    );
    return signal;
  };
}

```

**Comment by thejackshelton** [comment]
Wasn't able to get this working without a qvisible, which imo defeats the point of Qwik. Don't let me stop y'all from taking a shot at it though. I think that's a good way there!

**Comment by thejackshelton** [comment]
https://github.com/thejackshelton/astro-qwik-global-state-example/

I'm going to close this issue, because I think we actually have a nice story with global state management in Qwik with custom events. @josemarcilio, I overlooked your initial question because I assumed the custom event experience was not that great, and it's actually much better than I expected. 

Above I've created a template for you to see how I did it. I used the document to dispatch the event. Sorry for the late response!

It is also evident that there are unintended drawbacks with nanostores and global signals that the developer is expected to understand in other frameworks.

> While it is possible to use global state and computations, Context is sometimes a better solution. Additionally, it is important to note that global state should not be used in SSR (server side rendering) solutions, such as Solid Start. On the server, global state is shared across requests, and the lack of data isolation can (and will) lead to bugs, memory leaks and has security implications. It is recommended that application state should always be provided via context instead of relying on global.
