### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by PaulieScanlon** [QwikDev/astro#54]
Hello Mr @thejackshelton, not sure if it's this package or some other dependancy... but 

I didn't have typescript installed in my Astro project, and it's not named as peer dependency in this package so Astro errored when i spun up the dev server. 

Simple fix of course, i just installed typescript, but it might be helpful if its mentioned as part of the install scripts, e.g

```
# Using NPM
npx astro add @qwikdev/astro typescript
 
# Using Yarn
yarn astro add @qwikdev/astro typescript
 
# Using PNPM
pnpm astro add @qwikdev/astro typescript
```

**Comment by thejackshelton** [comment]
> Hello Mr @thejackshelton, not sure if it's this package or some other dependancy... but
> 
> I didn't have typescript installed in my Astro project, and it's not named as peer dependency in this package so Astro errored when i spun up the dev server.
> 
> Simple fix of course, i just installed typescript, but it might be helpful if its mentioned as part of the install scripts, e.g
> 
> ```
> # Using NPM
> npx astro add @qwikdev/astro typescript
>  
> # Using Yarn
> yarn astro add @qwikdev/astro typescript
>  
> # Using PNPM
> pnpm astro add @qwikdev/astro typescript
> ```

Ah good point! Let me go do that :)

**Comment by thejackshelton** [comment]
Ah yeah, so when you start a new Astro project it adds TypeScript already. Should I bother with it? Maybe a note to add it in the readme for existing p
<img width="413" alt="image" src="https://github.com/QwikDev/astro/assets/104264123/28d0dd15-cf0b-4bcb-b063-1b3d998aec9e">
rojects?

That is running the Astro CLI without adding the qwik integration yet.

**Comment by PaulieScanlon** [comment]
Hey mate, yes, you're correct, with a new Astro project Typescript is installed but you can uninstall it and Astro still works, where as, Qwik errors so arguably, it should be installed as a peer dep.

**Comment by thejackshelton** [comment]
> Hey mate, yes, you're correct, with a new Astro project Typescript is installed but you can uninstall it and Astro still works, where as, Qwik errors so arguably, it should be installed as a peer dep.

Sounds good, will add it as a peer dep now :)

**Comment by thejackshelton** [comment]
Should be fixed in 0.3.8 😄

**Comment by PaulieScanlon** [comment]
The man, the legend! Always so Qwik 😊

**Comment by thejackshelton** [comment]
> The man, the legend! Always so Qwik 😊

Haha gotta stay on brand.
