### ISSUE TITLE
Using Flowbite UI library

### ISSUE THREAD

**Issue by leelonghui3** [QwikDev/astro#6]
Bringing Qwik into Astro is exciting, but how can I use Flowbite in the Qwik + Astro setup?

I don't think [this is](https://flowbite.com/docs/getting-started/qwik/) the right method for me to follow, or is it?

**Comment by thejackshelton** [comment]
> Bringing Qwik into Astro is exciting, but how can I use Flowbite in the Qwik + Astro setup?
> 
> I don't think [this is](https://flowbite.com/docs/getting-started/qwik/) the right method for me to follow, or is it?

Because Astro is the meta-framework here, we'd likely want to follow their integration, and then add the Qwik integration

**Comment by leelonghui3** [comment]
Cool. Thanks for your prompt reply!

**Comment by thejackshelton** [comment]
> Cool. Thanks for your prompt reply!

Sure thing, I'm gonna close this issue. Happy to re-open it if you come across any Qwik specific issues!
