### ISSUE TITLE
/build/null in Chrome

### ISSUE THREAD

**Issue by sotasan** [QwikDev/astro#86]
After creating a new Astro project and adding Qwik, I have added the example Counter:

```ts
import { component$, useSignal } from "@builder.io/qwik";

export const Counter = component$(() => {
    const counter = useSignal(0);

    return <button onClick$={() => counter.value++}>{counter.value}</button>;
});
```

After interacting with it in the production build, it fetches the framework and component correctly. But in only in Chrome it also tries to load `http://localhost:4321/build/null`, otherwise the component is working correctly:

<img width="699" alt="grafik" src="https://github.com/QwikDev/astro/assets/39193720/d32311bc-cb58-4ac0-8b29-b2570b35925b">

**Comment by thejackshelton** [comment]
Hey @sotasan! I believe this is actually a bug in the Qwik core service worker. It seems to make an extra null fetch when it shouldn't be.

I would make an issue in the Qwik repo for this. Also side note: I would explicitly mention the Qwik core service worker, as there is another implementation in Qwik City that is being deprecated in the near future.

**Comment by sotasan** [comment]
Okay thanks, I have created the Issue in BuilderIO/qwik#6088.

**Comment by thejackshelton** [comment]
Thanks for that! I will go ahead and investigate this in core.

**Comment by thejackshelton** [comment]
@sotasan I have made a PR for a fix 😄

**Comment by sotasan** [comment]
Thanks for fixing the Issue!
